const STORAGE_KEY='panaderiaDemoV1';
const LOGIN_KEY='panaderiaDemoLogin';
const demoData={
  clients:[
    {id:'c1',name:'Supermercado Central',rut:'76.123.456-7',business:'Supermercado',address:'Av. Principal 120',commune:'Cunco',phone:'+56 9 5555 1111',contact:'Carolina',route:'Cunco',oven:true,active:true},
    {id:'c2',name:'Minimarket Los Robles',rut:'77.234.567-8',business:'Minimarket',address:'Los Robles 45',commune:'Melipeuco',phone:'+56 9 5555 2222',contact:'Javier',route:'Melipeuco',oven:false,active:true},
    {id:'c3',name:'Comercial San José',rut:'76.345.678-9',business:'Almacén',address:'O Higgins 332',commune:'Pitrufquén',phone:'+56 9 5555 3333',contact:'José',route:'Pitrufquén',oven:true,active:true},
    {id:'c4',name:'Almacén El Trigal',rut:'78.456.789-0',business:'Almacén',address:'Camino Rural km 3',commune:'Freire',phone:'+56 9 5555 4444',contact:'María',route:'Freire',oven:false,active:true}
  ],
  orders:[
    {id:1001,clientId:'c1',hallulla:40,marraqueta:42,ciabatta:0,date:'2026-10-02',status:'En producción',notes:'Entrega por la mañana'},
    {id:1002,clientId:'c2',hallulla:0,marraqueta:45,ciabatta:0,date:'2026-10-02',status:'Pendiente',notes:''},
    {id:1003,clientId:'c3',hallulla:50,marraqueta:0,ciabatta:24,date:'2026-10-02',status:'Despachado',notes:''},
    {id:1004,clientId:'c4',hallulla:31,marraqueta:0,ciabatta:0,date:'2026-10-02',status:'Entregado',notes:''}
  ],
  guides:[
    {id:'g1',number:'5012',clientId:'c1',date:'2026-10-01',kg:82,total:145000,paid:0,status:'Pendiente',notes:''},
    {id:'g2',number:'5013',clientId:'c2',date:'2026-10-01',kg:45,total:98500,paid:50000,status:'Parcial',notes:'Abono recibido'},
    {id:'g3',number:'5014',clientId:'c3',date:'2026-09-30',kg:74,total:132000,paid:132000,status:'Pagada',notes:''}
  ],
  payments:[
    {id:'p1',guideId:'g2',clientId:'c2',date:'2026-10-02',amount:50000,method:'Transferencia',notes:'Abono'},
    {id:'p2',guideId:'g3',clientId:'c3',date:'2026-10-01',amount:132000,method:'Transferencia',notes:'Pago total'}
  ],
  trays:[
    {clientId:'c1',delivered:18,returned:14,last:'2026-10-02'},
    {clientId:'c2',delivered:10,returned:10,last:'2026-10-01'},
    {clientId:'c3',delivered:22,returned:17,last:'2026-10-02'},
    {clientId:'c4',delivered:8,returned:6,last:'2026-09-30'}
  ],
  ovens:[
    {id:'o1',clientId:'c1',model:'UNOX XEFR-03EU-ETDV',installed:'2026-08-20',status:'Operativo',notes:'Comodato'},
    {id:'o2',clientId:'c3',model:'UNOX XEFR-03EU-ETDV',installed:'2026-08-22',status:'Operativo',notes:'Comodato'}
  ]
};
let db=loadData();
let currentModalAction=null;
let currentEditId=null;
const el=id=>document.getElementById(id);
const money=n=>new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(Number(n||0));
const fmtDate=d=>{if(!d)return'';const [y,m,day]=d.split('-');return `${day}-${m}-${y}`};
const uid=p=>(p+Date.now().toString(36)+Math.random().toString(36).slice(2,6));
function loadData(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||structuredClone(demoData)}catch{return structuredClone(demoData)}}
function saveData(){localStorage.setItem(STORAGE_KEY,JSON.stringify(db));renderAll()}
function getClient(id){return db.clients.find(c=>c.id===id)}
function orderKg(o){return Number(o.hallulla||0)+Number(o.marraqueta||0)+Number(o.ciabatta||0)}
function orderProducts(o){return [['Hallulla',o.hallulla],['Marraqueta',o.marraqueta],['Ciabatta',o.ciabatta]].filter(x=>Number(x[1])>0).map(x=>`${x[0]} ${x[1]} kg`).join(' · ')||'-'}
function guideBalance(g){return Math.max(0,Number(g.total||0)-Number(g.paid||0))}
function clientBalance(id){return db.guides.filter(g=>g.clientId===id).reduce((s,g)=>s+guideBalance(g),0)}
function clientTrayBalance(id){const t=db.trays.find(x=>x.clientId===id);return t?Number(t.delivered)-Number(t.returned):0}
function badge(text){const map={'Pendiente':'badge-yellow','En producción':'badge-blue','Preparado':'badge-blue','Despachado':'badge-gray','Entregado':'badge-green','Pagada':'badge-green','Parcial':'badge-blue','Operativo':'badge-green','Mantención':'badge-yellow','Inactivo':'badge-red'};return `<span class="badge-soft ${map[text]||'badge-gray'}">${text}</span>`}
function toast(msg){const n=document.createElement('div');n.className='toast-msg';n.textContent=msg;el('toastBox').appendChild(n);setTimeout(()=>n.remove(),3300)}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
function showApp(){el('loginView').classList.add('d-none');el('appView').classList.remove('d-none');navigate('dashboard')}
function logout(){sessionStorage.removeItem(LOGIN_KEY);el('appView').classList.add('d-none');el('loginView').classList.remove('d-none')}
function navigate(section){document.querySelectorAll('.app-section').forEach(x=>x.classList.remove('active-section'));el('section-'+section).classList.add('active-section');document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.section===section));const titles={dashboard:['Panel de control','Resumen general de la operación'],clientes:['Clientes','Registro comercial y operativo'],pedidos:['Pedidos','Registro y seguimiento de pedidos'],despachos:['Despachos','Control del avance de entregas'],guias:['Guías de despacho','Control documental y estado de pago'],pagos:['Pagos','Abonos y pagos recibidos'],bandejas:['Bandejas','Saldos de bandejas por cliente'],hornos:['Hornos','Equipos en comodato'],informes:['Informes','Resumen de ventas y cobranza'],configuracion:['Configuración','Opciones de la demostración']};el('pageTitle').textContent=titles[section][0];el('pageSubtitle').textContent=titles[section][1];el('sidebar')?.classList.remove('open');renderAll()}
function renderDashboard(){const today='2026-10-02';const todayOrders=db.orders.filter(o=>o.date===today);const todayKg=todayOrders.reduce((s,o)=>s+orderKg(o),0);const receivable=db.guides.reduce((s,g)=>s+guideBalance(g),0);el('dashboardStats').innerHTML=stat('bi-bag-check','Pedidos de hoy',todayOrders.length,`${todayOrders.filter(o=>o.status==='Pendiente').length} pendientes`)+stat('bi-box-seam','Kg pedidos hoy',`${todayKg.toFixed(2)} kg`,'Total registrado')+stat('bi-people','Clientes activos',db.clients.filter(c=>c.active).length,'Con registro activo')+stat('bi-cash-stack','Por cobrar',money(receivable),`${db.guides.filter(g=>guideBalance(g)>0).length} guías con saldo`);
  el('dashboardOrders').innerHTML=db.orders.slice().sort((a,b)=>b.id-a.id).slice(0,5).map(o=>`<tr><td><strong>${escapeHtml(getClient(o.clientId)?.name||'Cliente')}</strong></td><td>${orderKg(o).toFixed(2)} kg</td><td>${fmtDate(o.date)}</td><td>${badge(o.status)}</td></tr>`).join('')||emptyRow(4);
  const pending=db.orders.filter(o=>['Pendiente','En producción','Preparado'].includes(o.status)).length;const overdue=db.guides.filter(g=>guideBalance(g)>0).length;const tray=db.trays.filter(t=>Number(t.delivered)-Number(t.returned)>0).length;el('dashboardAlerts').innerHTML=`<div class="alert-item warning"><i class="bi bi-exclamation-triangle"></i><div><strong>${pending} pedidos en proceso</strong><div>Revisar producción y despacho.</div></div></div><div class="alert-item danger"><i class="bi bi-cash"></i><div><strong>${overdue} guías con saldo</strong><div>Total por cobrar: ${money(receivable)}.</div></div></div><div class="alert-item info"><i class="bi bi-boxes"></i><div><strong>${tray} clientes con bandejas pendientes</strong><div>Revisar devolución de bandejas.</div></div></div>`}
function stat(icon,label,value,small){return `<div class="stat-card"><div class="stat-icon"><i class="bi ${icon}"></i></div><div><span>${label}</span><strong>${value}</strong><small>${small}</small></div></div>`}
function emptyRow(cols){return `<tr><td colspan="${cols}" class="text-center text-muted py-4">Sin registros</td></tr>`}
function renderClients(){const q=(el('clientSearch')?.value||'').toLowerCase();const rows=db.clients.filter(c=>[c.name,c.rut,c.commune].some(v=>(v||'').toLowerCase().includes(q))).map(c=>`<tr><td><strong>${escapeHtml(c.name)}</strong><div class="text-muted small">${escapeHtml(c.contact||'')}</div></td><td>${escapeHtml(c.rut||'-')}</td><td>${escapeHtml(c.commune||'-')}</td><td>${escapeHtml(c.route||'-')}</td><td>${c.oven?badge('Operativo'):badge('Inactivo')}</td><td class="${clientBalance(c.id)>0?'money-pending':'money-positive'}">${money(clientBalance(c.id))}</td><td>${clientTrayBalance(c.id)}</td><td><button class="icon-btn" onclick="openClientDetail('${c.id}')"><i class="bi bi-eye"></i></button> <button class="icon-btn" onclick="editClient('${c.id}')"><i class="bi bi-pencil"></i></button></td></tr>`).join('');el('clientsTable').innerHTML=rows||emptyRow(8)}
function renderOrders(){const q=(el('orderSearch')?.value||'').toLowerCase();const f=el('orderStatusFilter')?.value||'';const list=db.orders.filter(o=>(getClient(o.clientId)?.name||'').toLowerCase().includes(q)&&(!f||o.status===f));el('ordersTable').innerHTML=list.slice().sort((a,b)=>b.id-a.id).map(o=>`<tr><td>#${o.id}</td><td><strong>${escapeHtml(getClient(o.clientId)?.name||'')}</strong></td><td>${escapeHtml(orderProducts(o))}</td><td><strong>${orderKg(o).toFixed(2)} kg</strong></td><td>${fmtDate(o.date)}</td><td>${badge(o.status)}</td><td><button class="icon-btn" onclick="cycleOrderStatus(${o.id})"><i class="bi bi-arrow-repeat"></i></button> <button class="icon-btn" onclick="editOrder(${o.id})"><i class="bi bi-pencil"></i></button></td></tr>`).join('')||emptyRow(7);const counts=s=>db.orders.filter(o=>o.status===s).length;el('orderStats').innerHTML=mini('Total',db.orders.length)+mini('Pendientes',counts('Pendiente'))+mini('En producción',counts('En producción'))+mini('Entregados',counts('Entregado'))}
function mini(label,val){return `<div class="mini-stat"><span>${label}</span><strong>${val}</strong></div>`}
function renderDispatch(){el('dispatchTable').innerHTML=db.orders.slice().sort((a,b)=>a.date.localeCompare(b.date)).map(o=>`<tr><td>#${o.id}</td><td>${escapeHtml(getClient(o.clientId)?.name||'')}</td><td>${orderKg(o).toFixed(2)} kg</td><td>${fmtDate(o.date)}</td><td>${badge(o.status)}</td><td><button class="icon-btn" onclick="cycleOrderStatus(${o.id})"><i class="bi bi-arrow-right-circle"></i> Avanzar</button></td></tr>`).join('')||emptyRow(6)}
function renderGuides(){const q=(el('guideSearch')?.value||'').toLowerCase();const f=el('guideStatusFilter')?.value||'';const list=db.guides.filter(g=>((g.number||'').toLowerCase().includes(q)||(getClient(g.clientId)?.name||'').toLowerCase().includes(q))&&(!f||g.status===f));el('guidesTable').innerHTML=list.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(g=>`<tr><td><strong>N° ${escapeHtml(g.number)}</strong></td><td>${escapeHtml(getClient(g.clientId)?.name||'')}</td><td>${fmtDate(g.date)}</td><td>${Number(g.kg).toFixed(2)} kg</td><td>${money(g.total)}</td><td>${money(g.paid)}</td><td class="${guideBalance(g)>0?'money-pending':'money-positive'}">${money(guideBalance(g))}</td><td>${badge(g.status)}</td><td><button class="icon-btn" onclick="editGuide('${g.id}')"><i class="bi bi-pencil"></i></button></td></tr>`).join('')||emptyRow(9);const total=db.guides.reduce((s,g)=>s+Number(g.total||0),0),paid=db.guides.reduce((s,g)=>s+Number(g.paid||0),0);el('guideStats').innerHTML=mini('Guías',db.guides.length)+mini('Facturado',money(total))+mini('Pagado',money(paid))+mini('Por cobrar',money(total-paid))}
function renderPayments(){el('paymentsTable').innerHTML=db.payments.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(p=>{const g=db.guides.find(x=>x.id===p.guideId);return `<tr><td>${fmtDate(p.date)}</td><td>${escapeHtml(getClient(p.clientId)?.name||'')}</td><td>${g?'N° '+escapeHtml(g.number):'-'}</td><td class="money-positive">${money(p.amount)}</td><td>${escapeHtml(p.method||'')}</td><td>${escapeHtml(p.notes||'-')}</td></tr>`}).join('')||emptyRow(6);const paid=db.payments.reduce((s,p)=>s+Number(p.amount||0),0),balance=db.guides.reduce((s,g)=>s+guideBalance(g),0);el('paymentStats').innerHTML=mini('Pagos registrados',db.payments.length)+mini('Total recibido',money(paid))+mini('Por cobrar',money(balance))+mini('Guías saldadas',db.guides.filter(g=>guideBalance(g)===0).length)}
function renderTrays(){el('traysTable').innerHTML=db.trays.map(t=>{const bal=Number(t.delivered)-Number(t.returned);return `<tr><td><strong>${escapeHtml(getClient(t.clientId)?.name||'')}</strong></td><td>${t.delivered}</td><td>${t.returned}</td><td>${bal}</td><td>${fmtDate(t.last)}</td><td><button class="icon-btn" onclick="openTrayModal('${t.clientId}')"><i class="bi bi-plus-circle"></i></button></td></tr>`}).join('')||emptyRow(6)}
function renderOvens(){el('ovensTable').innerHTML=db.ovens.map(o=>`<tr><td><strong>${escapeHtml(getClient(o.clientId)?.name||'')}</strong></td><td>${escapeHtml(o.model||'-')}</td><td>${fmtDate(o.installed)}</td><td>${badge(o.status)}</td><td>${escapeHtml(o.notes||'-')}</td><td><button class="icon-btn" onclick="editOven('${o.id}')"><i class="bi bi-pencil"></i></button></td></tr>`).join('')||emptyRow(6)}
function renderReports(){const totalKg=db.orders.reduce((s,o)=>s+orderKg(o),0),sales=db.guides.reduce((s,g)=>s+Number(g.total||0),0),received=db.payments.reduce((s,p)=>s+Number(p.amount||0),0),due=db.guides.reduce((s,g)=>s+guideBalance(g),0);el('reportCards').innerHTML=stat('bi-box-seam','Kg registrados',totalKg.toFixed(2),'Pedidos')+stat('bi-receipt','Total guías',money(sales),'Monto registrado')+stat('bi-cash-coin','Pagos recibidos',money(received),'Histórico demo')+stat('bi-exclamation-circle','Por cobrar',money(due),'Saldo de guías');const byClient=db.clients.map(c=>({name:c.name,kg:db.orders.filter(o=>o.clientId===c.id).reduce((s,o)=>s+orderKg(o),0)})).sort((a,b)=>b.kg-a.kg);const max=Math.max(1,...byClient.map(x=>x.kg));el('reportClientKg').innerHTML=byClient.map(x=>`<div class="report-row"><div class="report-row-head"><span>${escapeHtml(x.name)}</span><strong>${x.kg.toFixed(2)} kg</strong></div><div class="report-bar"><span style="width:${Math.round(x.kg/max*100)}%"></span></div></div>`).join('');const rec=db.clients.map(c=>({name:c.name,balance:clientBalance(c.id)})).filter(x=>x.balance>0).sort((a,b)=>b.balance-a.balance);el('reportReceivables').innerHTML=rec.map(x=>`<div class="report-row-head py-2 border-bottom"><span>${escapeHtml(x.name)}</span><strong class="money-pending">${money(x.balance)}</strong></div>`).join('')||'<p class="text-muted">No hay saldos pendientes.</p>'}
function renderAll(){renderDashboard();renderClients();renderOrders();renderDispatch();renderGuides();renderPayments();renderTrays();renderOvens();renderReports()}
function selectClients(selected=''){return db.clients.filter(c=>c.active).map(c=>`<option value="${c.id}" ${c.id===selected?'selected':''}>${escapeHtml(c.name)}</option>`).join('')}
function openModal(action,id=null){currentModalAction=action;currentEditId=id;let title='',sub='',body='';if(action==='client'){const c=id?db.clients.find(x=>x.id===id):{};title=id?'Editar cliente':'Nuevo cliente';sub='Datos comerciales y operativos';body=`<div class="form-grid"><div><label class="form-label">Nombre / Razón social</label><input name="name" class="form-control" value="${escapeHtml(c.name||'')}" required></div><div><label class="form-label">RUT</label><input name="rut" class="form-control" value="${escapeHtml(c.rut||'')}"></div><div><label class="form-label">Giro</label><input name="business" class="form-control" value="${escapeHtml(c.business||'')}"></div><div><label class="form-label">Contacto</label><input name="contact" class="form-control" value="${escapeHtml(c.contact||'')}"></div><div><label class="form-label">Teléfono</label><input name="phone" class="form-control" value="${escapeHtml(c.phone||'')}"></div><div><label class="form-label">Comuna</label><input name="commune" class="form-control" value="${escapeHtml(c.commune||'')}"></div><div><label class="form-label">Ruta</label><input name="route" class="form-control" value="${escapeHtml(c.route||'')}"></div><div><label class="form-label">Horno en comodato</label><select name="oven" class="form-select"><option value="false">No</option><option value="true" ${c.oven?'selected':''}>Sí</option></select></div><div class="full"><label class="form-label">Dirección</label><input name="address" class="form-control" value="${escapeHtml(c.address||'')}"></div></div>`}
if(action==='order'){const o=id?db.orders.find(x=>x.id===id):{};title=id?'Editar pedido':'Nuevo pedido';sub='Productos, kilos y fecha de entrega';body=`<div class="form-grid"><div class="full"><label class="form-label">Cliente</label><select name="clientId" class="form-select" required><option value="">Seleccione...</option>${selectClients(o.clientId)}</select></div><div><label class="form-label">Hallulla (kg)</label><input name="hallulla" type="number" step="0.01" min="0" class="form-control" value="${o.hallulla||0}"></div><div><label class="form-label">Marraqueta (kg)</label><input name="marraqueta" type="number" step="0.01" min="0" class="form-control" value="${o.marraqueta||0}"></div><div><label class="form-label">Ciabatta (kg)</label><input name="ciabatta" type="number" step="0.01" min="0" class="form-control" value="${o.ciabatta||0}"></div><div><label class="form-label">Fecha entrega</label><input name="date" type="date" class="form-control" value="${o.date||'2026-10-02'}" required></div><div><label class="form-label">Estado</label><select name="status" class="form-select">${['Pendiente','En producción','Preparado','Despachado','Entregado'].map(s=>`<option ${o.status===s?'selected':''}>${s}</option>`).join('')}</select></div><div class="full"><label class="form-label">Observaciones</label><textarea name="notes" class="form-control">${escapeHtml(o.notes||'')}</textarea></div></div>`}
if(action==='guide'){const g=id?db.guides.find(x=>x.id===id):{};title=id?'Editar guía':'Nueva guía';sub='Registro de guía de despacho';body=`<div class="form-grid"><div><label class="form-label">N° Guía</label><input name="number" class="form-control" value="${escapeHtml(g.number||'')}" required></div><div><label class="form-label">Fecha</label><input name="date" type="date" class="form-control" value="${g.date||'2026-10-02'}" required></div><div class="full"><label class="form-label">Cliente</label><select name="clientId" class="form-select" required><option value="">Seleccione...</option>${selectClients(g.clientId)}</select></div><div><label class="form-label">Kg</label><input name="kg" type="number" step="0.01" min="0" class="form-control" value="${g.kg||0}"></div><div><label class="form-label">Monto total</label><input name="total" type="number" min="0" class="form-control" value="${g.total||0}" required></div><div class="full"><label class="form-label">Observaciones</label><textarea name="notes" class="form-control">${escapeHtml(g.notes||'')}</textarea></div></div>`}
if(action==='payment'){const pending=db.guides.filter(g=>guideBalance(g)>0);title='Registrar pago';sub='Asociar abono o pago a una guía';body=`<div class="form-grid"><div class="full"><label class="form-label">Guía</label><select id="paymentGuide" name="guideId" class="form-select" required><option value="">Seleccione...</option>${pending.map(g=>`<option value="${g.id}">N° ${escapeHtml(g.number)} · ${escapeHtml(getClient(g.clientId)?.name||'')} · saldo ${money(guideBalance(g))}</option>`).join('')}</select></div><div><label class="form-label">Monto</label><input name="amount" type="number" min="1" class="form-control" required></div><div><label class="form-label">Fecha</label><input name="date" type="date" class="form-control" value="2026-10-02" required></div><div><label class="form-label">Medio</label><select name="method" class="form-select"><option>Transferencia</option><option>Efectivo</option><option>Débito</option><option>Crédito</option><option>Otro</option></select></div><div class="full"><label class="form-label">Observación</label><input name="notes" class="form-control"></div></div>`}
if(action==='tray'){const t=db.trays.find(x=>x.clientId===id);title='Movimiento de bandejas';sub=getClient(id)?.name||'';body=`<input type="hidden" name="clientId" value="${id}"><div class="detail-card mb-3">Saldo actual: <strong>${clientTrayBalance(id)}</strong> bandejas</div><div class="form-grid"><div><label class="form-label">Tipo</label><select name="type" class="form-select"><option value="deliver">Entregadas al cliente</option><option value="return">Devueltas por cliente</option></select></div><div><label class="form-label">Cantidad</label><input name="qty" type="number" min="1" class="form-control" required></div><div><label class="form-label">Fecha</label><input name="date" type="date" class="form-control" value="2026-10-02"></div></div>`}
if(action==='oven'){const o=id?db.ovens.find(x=>x.id===id):{};title=id?'Editar horno':'Registrar horno';sub='Equipo en comodato';body=`<div class="form-grid"><div class="full"><label class="form-label">Cliente</label><select name="clientId" class="form-select" required><option value="">Seleccione...</option>${selectClients(o.clientId)}</select></div><div><label class="form-label">Modelo</label><input name="model" class="form-control" value="${escapeHtml(o.model||'UNOX XEFR-03EU-ETDV')}"></div><div><label class="form-label">Instalación</label><input name="installed" type="date" class="form-control" value="${o.installed||'2026-10-02'}"></div><div><label class="form-label">Estado</label><select name="status" class="form-select">${['Operativo','Mantención','Inactivo'].map(s=>`<option ${o.status===s?'selected':''}>${s}</option>`).join('')}</select></div><div class="full"><label class="form-label">Observaciones</label><textarea name="notes" class="form-control">${escapeHtml(o.notes||'')}</textarea></div></div>`}
el('modalTitle').textContent=title;el('modalSubtitle').textContent=sub;el('modalBody').innerHTML=body;bootstrap.Modal.getOrCreateInstance(el('entityModal')).show()}
function formObj(form){return Object.fromEntries(new FormData(form).entries())}
function saveModal(e){e.preventDefault();const v=formObj(e.target);if(currentModalAction==='client'){const obj={id:currentEditId||uid('c'),name:v.name,rut:v.rut,business:v.business,address:v.address,commune:v.commune,phone:v.phone,contact:v.contact,route:v.route,oven:v.oven==='true',active:true};if(currentEditId)db.clients=db.clients.map(x=>x.id===currentEditId?obj:x);else db.clients.push(obj);toast('Cliente guardado')}
if(currentModalAction==='order'){const obj={id:currentEditId||Math.max(1000,...db.orders.map(x=>Number(x.id)))+1,clientId:v.clientId,hallulla:Number(v.hallulla||0),marraqueta:Number(v.marraqueta||0),ciabatta:Number(v.ciabatta||0),date:v.date,status:v.status,notes:v.notes};if(orderKg(obj)<=0)return alert('Ingrese al menos un producto con kilos.');if(currentEditId)db.orders=db.orders.map(x=>x.id===currentEditId?obj:x);else db.orders.push(obj);toast('Pedido guardado')}
if(currentModalAction==='guide'){const old=currentEditId?db.guides.find(x=>x.id===currentEditId):null;const obj={id:currentEditId||uid('g'),number:v.number,clientId:v.clientId,date:v.date,kg:Number(v.kg||0),total:Number(v.total||0),paid:old?Number(old.paid||0):0,status:'Pendiente',notes:v.notes};obj.status=obj.paid<=0?'Pendiente':obj.paid>=obj.total?'Pagada':'Parcial';if(currentEditId)db.guides=db.guides.map(x=>x.id===currentEditId?obj:x);else db.guides.push(obj);toast('Guía guardada')}
if(currentModalAction==='payment'){const g=db.guides.find(x=>x.id===v.guideId);if(!g)return;const amount=Number(v.amount||0);if(amount<=0||amount>guideBalance(g))return alert(`El monto debe ser mayor a 0 y no superar ${money(guideBalance(g))}.`);g.paid=Number(g.paid||0)+amount;g.status=g.paid>=g.total?'Pagada':'Parcial';db.payments.push({id:uid('p'),guideId:g.id,clientId:g.clientId,date:v.date,amount,method:v.method,notes:v.notes});toast('Pago registrado')}
if(currentModalAction==='tray'){let t=db.trays.find(x=>x.clientId===v.clientId);if(!t){t={clientId:v.clientId,delivered:0,returned:0,last:v.date};db.trays.push(t)}const q=Number(v.qty||0);if(v.type==='deliver')t.delivered+=q;else t.returned+=q;t.last=v.date;toast('Movimiento de bandejas registrado')}
if(currentModalAction==='oven'){const obj={id:currentEditId||uid('o'),clientId:v.clientId,model:v.model,installed:v.installed,status:v.status,notes:v.notes};if(currentEditId)db.ovens=db.ovens.map(x=>x.id===currentEditId?obj:x);else db.ovens.push(obj);const c=getClient(v.clientId);if(c)c.oven=v.status!=='Inactivo';toast('Horno guardado')}
saveData();bootstrap.Modal.getInstance(el('entityModal')).hide()}
function editClient(id){openModal('client',id)}function editOrder(id){openModal('order',id)}function editGuide(id){openModal('guide',id)}function openTrayModal(id){openModal('tray',id)}function editOven(id){openModal('oven',id)}
function cycleOrderStatus(id){const o=db.orders.find(x=>x.id===id);if(!o)return;const states=['Pendiente','En producción','Preparado','Despachado','Entregado'];o.status=states[(states.indexOf(o.status)+1)%states.length];saveData();toast(`Pedido #${id}: ${o.status}`)}
function openClientDetail(id){const c=getClient(id);if(!c)return;const orders=db.orders.filter(o=>o.clientId===id),guides=db.guides.filter(g=>g.clientId===id);el('modalTitle').textContent=c.name;el('modalSubtitle').textContent='Ficha del cliente';el('modalBody').innerHTML=`<div class="detail-grid"><div><small>RUT</small><strong>${escapeHtml(c.rut||'-')}</strong></div><div><small>Comuna</small><strong>${escapeHtml(c.commune||'-')}</strong></div><div><small>Ruta</small><strong>${escapeHtml(c.route||'-')}</strong></div><div><small>Horno</small><strong>${c.oven?'Sí':'No'}</strong></div><div><small>Pedidos</small><strong>${orders.length}</strong></div><div><small>Kg acumulados</small><strong>${orders.reduce((s,o)=>s+orderKg(o),0).toFixed(2)} kg</strong></div><div><small>Saldo guías</small><strong class="money-pending">${money(clientBalance(id))}</strong></div><div><small>Saldo bandejas</small><strong>${clientTrayBalance(id)}</strong></div></div><hr><h6>Guías del cliente</h6>${guides.map(g=>`<div class="report-row-head py-2 border-bottom"><span>N° ${escapeHtml(g.number)} · ${fmtDate(g.date)}</span><span>${money(guideBalance(g))} ${badge(g.status)}</span></div>`).join('')||'<p class="text-muted">Sin guías registradas.</p>'}`;el('modalSubmit').classList.add('d-none');bootstrap.Modal.getOrCreateInstance(el('entityModal')).show();el('entityModal').addEventListener('hidden.bs.modal',()=>el('modalSubmit').classList.remove('d-none'),{once:true})}
function exportData(){const blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='panaderia-demo-respaldo.json';a.click();URL.revokeObjectURL(a.href)}
function resetData(){if(!confirm('¿Restaurar todos los datos de demostración?'))return;db=structuredClone(demoData);saveData();toast('Datos demo restaurados')}
document.addEventListener('DOMContentLoaded',()=>{el('loginForm').addEventListener('submit',e=>{e.preventDefault();if(el('loginUser').value==='admin'&&el('loginPass').value==='demo123'){sessionStorage.setItem(LOGIN_KEY,'1');el('loginError').classList.add('d-none');showApp()}else el('loginError').classList.remove('d-none')});if(sessionStorage.getItem(LOGIN_KEY)==='1')showApp();document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.section)));document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>{const a=b.dataset.action;if(a==='new-order')openModal('order');if(a==='new-client')openModal('client');if(a==='new-guide')openModal('guide');if(a==='new-payment')openModal('payment');if(a==='new-tray'){const id=db.clients[0]?.id;if(id)openModal('tray',id)}if(a==='new-oven')openModal('oven')}));el('entityForm').addEventListener('submit',saveModal);el('logoutBtn').addEventListener('click',logout);el('mobileMenuBtn').addEventListener('click',()=>document.querySelector('.sidebar').classList.toggle('open'));el('clientSearch').addEventListener('input',renderClients);el('orderSearch').addEventListener('input',renderOrders);el('orderStatusFilter').addEventListener('change',renderOrders);el('guideSearch').addEventListener('input',renderGuides);el('guideStatusFilter').addEventListener('change',renderGuides);el('exportBtn').addEventListener('click',exportData);el('resetBtn').addEventListener('click',resetData);renderAll()});