(() => {
  const $=id=>document.getElementById(id), MONTH_KEY='panaderiaMesTrabajo', TARE=1.6;
  const esc=s=>String(s??'').replace(/[&<>'\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[m]));
  const money=n=>new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(Number(n||0));
  const kg=n=>Number(n||0).toLocaleString('es-CL',{minimumFractionDigits:2,maximumFractionDigits:3});
  const fmt=d=>{if(!d)return'-';const [y,m,day]=String(d).split('-');return`${day}-${m}-${y}`};
  const month=()=>localStorage.getItem(MONTH_KEY)||new Date().toISOString().slice(0,7);
  const monthLabel=ym=>{const[y,m]=ym.split('-').map(Number);return new Date(y,m-1,1).toLocaleDateString('es-CL',{month:'long',year:'numeric'}).replace(/^./,c=>c.toUpperCase())};
  const products=[['hallulla','Hallulla','priceHallulla'],['marraqueta','Marraqueta','priceMarraqueta'],['ciabatta','Ciabatta','priceCiabatta'],['medioBaguette','Medio baguette','priceMedioBaguette'],['panCompleto','Pan completo','pricePanCompleto']];
  const client=id=>(db.clients||[]).find(c=>String(c.id)===String(id));
  const grossPrice=(c,key)=>{const net=Number(c?.[key]||0);return net>0?Math.round(net*1.19):0};
  const totalKg=o=>products.reduce((s,[k])=>s+Number(o?.[k]||0),0);
  const clientOptions=selected=>(db.clients||[]).filter(c=>c.active!==false).slice().sort((a,b)=>String(a.name).localeCompare(String(b.name),'es')).map(c=>`<option value="${esc(c.id)}"${c.id===selected?' selected':''}>${esc(c.name)}</option>`).join('');

  function productCard(key,label,value){return `<div class="card-panel mb-3" style="padding:16px">
    <div class="d-flex justify-content-between gap-2 flex-wrap mb-2"><div><strong>${label}</strong><div class="small text-muted">Tara: ${TARE.toFixed(1)} kg/bandeja · Precio c/IVA: <strong data-price="${key}">-</strong></div></div><div class="text-end"><small class="text-muted d-block">Kilos acumulados</small><strong class="fs-5"><span data-total-label="${key}">${kg(value)}</span> kg</strong><small class="text-muted d-block">Subtotal: <span data-subtotal="${key}">$0</span></small></div></div>
    <input type="hidden" name="${key}" value="${Number(value||0)}" data-total="${key}">
    <div class="form-grid"><div><label class="form-label">N° bandejas</label><input type="number" min="0" step="1" class="form-control" data-trays="${key}"></div><div><label class="form-label">Peso que marca la pesa (kg)</label><input type="number" min="0" step="0.01" class="form-control" data-gross="${key}"></div><div class="full"><button type="button" class="primary-btn" data-add="${key}"><i class="bi bi-plus-circle"></i> Sumar pesaje</button></div></div>
    <div class="small mt-2" data-note="${key}"></div><div class="small text-muted mt-1" data-list="${key}">${Number(value||0)>0?`Inicial: ${kg(value)} kg`:''}</div>
  </div>`}

  function bindCalculator(){
    const modal=$('modalBody');if(!modal)return;
    const recalc=()=>{
      const c=client(modal.querySelector('[name="clientId"]')?.value);let kilos=0,amount=0;const missing=[];
      products.forEach(([key,label,priceKey])=>{const k=Number(modal.querySelector(`[data-total="${key}"]`)?.value||0),p=grossPrice(c,priceKey);kilos+=k;amount+=k*p;const pe=modal.querySelector(`[data-price="${key}"]`),se=modal.querySelector(`[data-subtotal="${key}"]`);if(pe)pe.textContent=p?`${money(p)}/kg`:'Sin precio';if(se)se.textContent=p?money(k*p):'-';if(k>0&&!p)missing.push(label)});
      if($('orderGrandTotal'))$('orderGrandTotal').textContent=`${kg(kilos)} kg`;if($('orderGuideTotal'))$('orderGuideTotal').textContent=money(Math.round(amount));const hidden=modal.querySelector('[name="guideTotal"]');if(hidden)hidden.value=Math.round(amount);
      const w=$('guidePriceWarning');if(w){w.textContent=missing.length?`Falta precio configurado para: ${missing.join(', ')}.`:'';w.classList.toggle('d-none',!missing.length)}
    };
    window.updateOrderGuideTotals=recalc;modal.querySelector('[name="clientId"]')?.addEventListener('change',recalc);
    products.forEach(([key])=>{const hidden=modal.querySelector(`[data-total="${key}"]`),lab=modal.querySelector(`[data-total-label="${key}"]`),note=modal.querySelector(`[data-note="${key}"]`),list=modal.querySelector(`[data-list="${key}"]`);modal.querySelector(`[data-add="${key}"]`)?.addEventListener('click',()=>{const trays=Number(modal.querySelector(`[data-trays="${key}"]`)?.value||0),gross=Number(modal.querySelector(`[data-gross="${key}"]`)?.value||0);if(gross<=0){alert('Ingresa el peso que marca la pesa.');return}const net=gross-trays*TARE;if(net<=0){alert('El peso neto no puede ser 0 o negativo.');return}const t=Number(hidden.value||0)+net;hidden.value=Number(t.toFixed(3));lab.textContent=kg(t);note.textContent=`${kg(gross)} kg − ${trays} bandeja${trays===1?'':'s'} × ${TARE.toFixed(1)} kg = ${kg(net)} kg de pan.`;list.innerHTML+=`${list.innerHTML?' · ':''}+ ${kg(net)} kg`;modal.querySelector(`[data-trays="${key}"]`).value='';modal.querySelector(`[data-gross="${key}"]`).value='';recalc()})});
    recalc();
  }

  function openOrder(id=null){
    const o=id?(db.orders||[]).find(x=>String(x.id)===String(id)):{};const g=id?(db.guides||[]).find(x=>x.id===`order-guide-${id}`):null;currentAction='order';currentEditId=id;$('modalTitle').textContent=id?'Editar pedido':'Ingresar pedido';$('modalSubtitle').textContent='Pesaje por bandejas y verificación del monto de la guía según precios del cliente.';$('modalSubmit').classList.remove('d-none');const d=new Date(),date=o.date||`${month()}-${String(d.getDate()).padStart(2,'0')}`;
    $('modalBody').innerHTML=`<div class="form-grid mb-3"><div class="full"><label class="form-label">Cliente</label><select name="clientId" class="form-select" required><option value="">Seleccione...</option>${clientOptions(o.clientId)}</select></div><div><label class="form-label">Fecha de entrega</label><input name="date" type="date" class="form-control" value="${esc(date)}" required></div><div><label class="form-label">N° de guía</label><input name="guideNumber" class="form-control" value="${esc(g?.number||'')}"></div><div><label class="form-label">Estado</label><select name="status" class="form-select">${['Pendiente','En producción','Preparado','Despachado','Entregado'].map(s=>`<option${(o.status||'Pendiente')===s?' selected':''}>${s}</option>`).join('')}</select></div></div>
    ${products.map(([k,l])=>productCard(k,l,o[k]||0)).join('')}
    <div class="card-panel mb-3" style="padding:16px"><div class="d-flex justify-content-between mb-2"><strong>Total kilos</strong><strong id="orderGrandTotal" class="fs-4">0,00 kg</strong></div><div class="d-flex justify-content-between"><strong>Monto calculado guía</strong><strong id="orderGuideTotal" class="fs-4">$0</strong></div><input type="hidden" name="guideTotal" value="0"><div id="guidePriceWarning" class="alert alert-warning py-2 mt-3 mb-0 d-none"></div></div><div><label class="form-label">Observaciones</label><textarea name="notes" class="form-control" rows="3">${esc(o.notes||'')}</textarea></div>`;
    bindCalculator();bootstrap.Modal.getOrCreateInstance($('entityModal')).show();
  }
  window.openDispatchOrderModal=openOrder;

  function ensureLayout(){
    const section=$('section-despachos');if(section&&!section.dataset.ordersOnly){section.dataset.ordersOnly='1';section.innerHTML=`<div class="section-toolbar"><div><h2 class="section-inline-title">Ingresar pedidos</h2><p class="muted mb-0">Pesajes acumulados y cálculo automático del monto de guía.</p></div><button id="newDispatchOrderBtn" class="primary-btn"><i class="bi bi-plus-circle"></i> Ingresar pedido</button></div><div class="card-panel"><div class="panel-head"><div><h2>Pedidos por despachar</h2><p id="pendingOrdersSubtitle"></p></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Entrega</th><th>Cliente</th><th>Productos</th><th>Total kg / Guía</th><th>Estado</th><th></th></tr></thead><tbody id="dispatchPendingOrders"></tbody></table></div></div>`;$('newDispatchOrderBtn')?.addEventListener('click',()=>openOrder())}
    if(!$('section-historial-despachos')){const s=document.createElement('section');s.id='section-historial-despachos';s.className='app-section';s.innerHTML=`<div class="section-toolbar"><div><h2 class="section-inline-title">Historial de despachos</h2><p class="muted mb-0">Consulta despachos por cliente, kilos y monto de guía.</p></div></div><div class="card-panel mb-3"><div class="filter-row"><div class="search-control"><i class="bi bi-search"></i><input id="dispatchClientSearch" placeholder="Buscar cliente..."></div><select id="dispatchClientFilter" class="form-select compact-select"><option value="">Todos los clientes</option></select></div></div><div id="dispatchSummary" class="mini-stats"></div><div class="card-panel"><div class="panel-head"><div><h2 id="dispatchTitle">Historial de despachos</h2><p id="dispatchSubtitle"></p></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Fecha</th><th>Cliente</th><th>Hallulla</th><th>Marraqueta</th><th>Ciabatta</th><th>Otros</th><th>Total kg</th><th>Guía</th><th>Monto guía</th></tr></thead><tbody id="dispatchHistoryTable"></tbody></table></div></div>`;document.querySelector('.main-content')?.insertBefore(s,$('section-configuracion')||null);$('dispatchClientSearch')?.addEventListener('input',renderHistory);$('dispatchClientFilter')?.addEventListener('change',renderHistory)}
    const nav=$('mainNav');if(nav&&!$('historyDispatchNav')){const b=document.createElement('button');b.id='historyDispatchNav';b.className='nav-item';b.innerHTML='<i class="bi bi-clock-history"></i><span>Historial despachos</span>';nav.insertBefore(b,nav.querySelector('[data-section="guias"]')||null);b.onclick=()=>{document.querySelectorAll('.app-section').forEach(x=>x.classList.remove('active-section'));$('section-historial-despachos')?.classList.add('active-section');document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('pageTitle').textContent='Historial de despachos';$('pageSubtitle').textContent='Despachos realizados y detalle por cliente';renderHistory()}}
  }

  function renderPending(){const tb=$('dispatchPendingOrders');if(!tb)return;const ms=month(),orders=(db.orders||[]).filter(o=>String(o.date||'').slice(0,7)===ms&&o.status!=='Entregado').sort((a,b)=>String(a.date).localeCompare(String(b.date)));tb.innerHTML=orders.length?orders.map(o=>{const parts=products.filter(([k])=>Number(o[k]||0)>0).map(([k,l])=>`${l}: ${kg(o[k])} kg`).join(' · '),g=(db.guides||[]).find(x=>x.id===`order-guide-${o.id}`);return`<tr><td>${fmt(o.date)}</td><td><strong>${esc(client(o.clientId)?.name||'Cliente')}</strong></td><td>${esc(parts||'-')}</td><td><strong>${kg(totalKg(o))} kg</strong>${g?`<div class="small text-muted">Guía N° ${esc(g.number)} · ${money(g.total)}</div>`:''}</td><td>${typeof badge==='function'?badge(o.status||'Pendiente'):esc(o.status||'Pendiente')}</td><td><button class="icon-btn" onclick="openDispatchOrderModal('${esc(o.id)}')"><i class="bi bi-pencil"></i></button></td></tr>`}).join(''):`<tr><td colspan="6" class="text-center text-muted py-4">No hay pedidos pendientes en ${monthLabel(ms)}.</td></tr>`;if($('pendingOrdersSubtitle'))$('pendingOrdersSubtitle').textContent=`${monthLabel(ms)} · ${orders.length} pedido${orders.length===1?'':'s'}`}
  function historyRows(){const ms=month(),hist=(window.panHistorial||[]).filter(r=>String(r.date||'').slice(0,7)===ms&&totalKg(r)>0);if(hist.length)return hist;return(db.guides||[]).filter(g=>String(g.date||'').slice(0,7)===ms).map(g=>({date:g.date,clientId:g.clientId,clientName:client(g.clientId)?.name||'Cliente',guide:g.number,amount:g.total,_guideOnly:true,kg:g.kg}))}
  const hname=r=>r.clientName||client(r.clientId)?.name||'Cliente';
  function renderHistory(){const tb=$('dispatchHistoryTable');if(!tb)return;const all=historyRows(),sel=$('dispatchClientFilter'),cur=sel?.value||'',names=[...new Set(all.map(hname))].sort((a,b)=>a.localeCompare(b,'es'));if(sel){sel.innerHTML='<option value="">Todos los clientes</option>'+names.map(n=>`<option value="${esc(n)}">${esc(n)}</option>`).join('');if(names.includes(cur))sel.value=cur}const q=($('dispatchClientSearch')?.value||'').toLowerCase(),chosen=sel?.value||'',rows=all.filter(r=>(!q||hname(r).toLowerCase().includes(q))&&(!chosen||hname(r)===chosen)).sort((a,b)=>String(b.date).localeCompare(String(a.date)));tb.innerHTML=rows.length?rows.map(r=>{const other=Number(r.medioBaguette||0)+Number(r.panCompleto||0),tk=r._guideOnly?Number(r.kg||0):totalKg(r);return`<tr><td>${fmt(r.date)}</td><td><strong>${esc(hname(r))}</strong></td><td>${Number(r.hallulla||0)?kg(r.hallulla)+' kg':'-'}</td><td>${Number(r.marraqueta||0)?kg(r.marraqueta)+' kg':'-'}</td><td>${Number(r.ciabatta||0)?kg(r.ciabatta)+' kg':'-'}</td><td>${other?kg(other)+' kg':'-'}</td><td><strong>${kg(tk)} kg</strong></td><td>${r.guide?`N° ${esc(r.guide)}`:'-'}</td><td><strong>${Number(r.amount||0)?money(r.amount):'-'}</strong></td></tr>`}).join(''):`<tr><td colspan="9" class="text-center text-muted py-4">Sin despachos en ${monthLabel(month())}.</td></tr>`;const total=rows.reduce((s,r)=>s+(r._guideOnly?Number(r.kg||0):totalKg(r)),0),amount=rows.reduce((s,r)=>s+Number(r.amount||0),0);if($('dispatchSummary')&&typeof mini==='function')$('dispatchSummary').innerHTML=mini('Despachos',rows.length)+mini('Clientes',new Set(rows.map(hname)).size)+mini('Total kilos',`${kg(total)} kg`)+mini('Monto guías',money(amount));if($('dispatchTitle'))$('dispatchTitle').textContent=chosen?`Historial de ${chosen}`:'Historial de despachos';if($('dispatchSubtitle'))$('dispatchSubtitle').textContent=monthLabel(month())}
  function render(){ensureLayout();renderPending();renderHistory()}
  function install(){ensureLayout();try{renderDispatch=render}catch{}window.renderDispatch=render;render();setTimeout(render,500)}
  window.addEventListener('DOMContentLoaded',install);window.addEventListener('load',()=>setTimeout(install,50));
})();